### ISSUE TITLE
I can't use the option

### ISSUE THREAD

**Issue by Alen-Mo** [salahdin-ahmed/sent#1]
$ sent -f aril test
usage: sent [file]
$ sent -b  red test 
usage: sent [file]

How can i change the color for the back ground and the font ?
Can you Explain ? 

Thanks :)

**Comment by salastro** [comment]
> usage: sent [file]

I think there is a problem with the version you compiled, the message of this fork should be `usage: sent [-c fgcolor] [-b bgcolor] [-f font] [file]`, `usage: sent [file]` is the usage message of the original program. In other words, go through the [installation](https://github.com/salahdin-ahmed/sent#install) process.

If you already had gone through it, maybe you have the original sent installed on your machine, try
```
$ which sent
```
and see where it is pointing and delete it.

> $ sent -b red test

You can not use color names, you can only use hexadecimal color codes (e.g. `#FF0000`).

**Comment by Alen-Mo** [comment]
I was install the original sent not this(fork). Now it's working good. 
Thanks salahdin-ahmed :)

**Comment by salastro** [comment]
Cool, you also may want to [patch your own sent](https://tools.suckless.org/sent/patches/).
You're welcome :)
